# Generated by Django 3.2.8 on 2021-11-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='actor',
            field=models.CharField(max_length=255, verbose_name='исполнитель/группа'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
